name: Build and Publish

on:
  push:
    tags:
      - 'v*' # Run this workflow only when a new version tag is pushed
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build project using rust:bookworm docker image
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            rust:bookworm \
            cargo build --release

      - name: Upload compiled binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: srvstat
          path: target/release/srvstat

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: srvstat

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: srvstat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
